---
functional:
 - Пользователь должен иметь возможность искать товары по ключевому слову или категории
 - Пользователь должен иметь возможность фильтровать товары
 - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
 - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
 - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
 - Сайт должен быть безопасным и защищать данные пользователя
 - Сайт нужно протестировать на совместимость с последними версиями браузеров
 - Важно, чтобы сайт мог обрабатывать большое количество трафика
 - Сайт должен быть доступен на различных устройствах
 - Сайт должен иметь мобильную версию
implicit:
 - Корзина должна храниться в сессии браузера
 - На странице корзины пользователь cможет удалить товар из корзины
 - Страница не должна перезагружаться при переходе с каталога в корзину и на страницу оплаты
 - сайт должен быть мультиязычен (русская и английская версии)
